import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { strToU8, zipSync } from 'fflate';
import { createBundle, fragmentsFor, sha256, validateBundle } from '../../shared/transfer';
import { readArchive } from '../../extension/archive';
const base = process.env.WEB_REVIEW_URL || 'http://127.0.0.1:4320'; if (base !== 'http://127.0.0.1:4320') throw new Error('Pinned to isolated review server 4320.');
const out = resolve('web/test-output'); await mkdir(out, { recursive: true }); const browser = await chromium.launch({ channel: 'chrome', headless: true }); const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' }); const page = await context.newPage(); const checks: string[] = [], errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
try {
 await page.goto(`${base}/register`); await page.getByLabel('称呼').fill('隔离高级验收'); await page.getByLabel('邮箱').fill(`advanced-${randomUUID()}@example.invalid`); await page.getByLabel('密码').fill(`Synthetic-${randomUUID()}!`); await page.getByRole('button', { name: '创建账号', exact: true }).click(); await page.waitForURL('**/inbox'); await page.goto(`${base}/settings/team`); await page.getByRole('heading', { name: /个人私有空间/ }).waitFor(); assert.equal(await page.getByRole('button', { name: '生成邀请链接' }).count(), 0); checks.push('Personal space cannot invite');
 await page.getByLabel('团队空间名称').fill('隔离明确分享团队'); await page.getByRole('button', { name: '创建空间', exact: true }).click(); await page.getByLabel('当前空间').locator('option', { hasText: '隔离明确分享团队' }).waitFor({ state: 'attached' }); const teamId = await page.getByLabel('当前空间').locator('option', { hasText: '隔离明确分享团队' }).getAttribute('value'); assert.ok(teamId); const privateId = await page.getByLabel('当前空间').inputValue(); await page.getByLabel('当前空间').selectOption(teamId); await page.getByRole('button', { name: '生成邀请链接' }).waitFor(); await page.getByLabel('当前空间').selectOption(privateId); checks.push('Create team + explicit workspace switch');
 const key = { platform: 'zsxq' as const, group_id: '101101', entity_type: 'topic' as const, entity_id: '202202' }; const quote = '这是超过摘要六百字符后的完整原文证据。'; const text = '完整原文前段。'.repeat(100) + '\n' + quote; const bytes = new Uint8Array(1024 * 1024 + 7); bytes.fill(66); const hash = sha256(bytes); const bundle = createBundle({ records: [{ source_key: key, group_id: key.group_id, author_id: '303303', author_name: '隔离测试作者', title: '超过六百字符与附件的隔离材料', text, created_at: '2026-10-01T00:00:00Z', source_url: 'https://wx.zsxq.com/dweb2/index/topic_detail/202202', captured_at: '2026-10-02T00:00:00Z', fragments: fragmentsFor(text), coverage: { body: 'complete', comments: 'partial', attachments: 'partial', reasons: ['合成验收，不访问第三方'] } }, ...Array.from({ length: 24 }, (_, i) => ({ source_key: { ...key, entity_id: String(202203 + i) }, group_id: key.group_id, author_id: '303303', author_name: '隔离测试作者', title: `隔离材料 · 返回列表 ${i + 1}`, source_url: `https://wx.zsxq.com/dweb2/index/topic_detail/${202203 + i}`, text: `完整原文列表状态还原测试 ${i + 1}`, created_at: '2026-10-01T00:00:00Z', captured_at: '2026-10-02T00:00:00Z', fragments: fragmentsFor(`完整原文列表状态还原测试 ${i + 1}`), coverage: { body: 'complete' as const, comments: 'partial' as const, attachments: 'partial' as const, reasons: ['隔离合成材料'] } }))], attachments: [{ id: 'portable-fixture-file', hash, size: bytes.length, name: 'isolated-original.bin', mime: 'application/octet-stream', record_source_key: key, status: 'available' }] }); const zip = zipSync({ 'bundle.json': strToU8(JSON.stringify(bundle)), [`attachments/${hash}`]: bytes });
 await page.goto(`${base}/settings/data`); const uploadRequests: { method: string; path: string }[] = []; page.on('request', r => { if (r.url().includes('/uploads')) uploadRequests.push({ method: r.method(), path: new URL(r.url()).pathname }); }); await page.getByLabel('选择迁移包').setInputFiles({ name: 'isolated-with-original.zip', mimeType: 'application/zip', buffer: Buffer.from(zip) }); await page.getByRole('button', { name: /^确认导入/ }).click(); await page.getByRole('heading', { name: '服务端导入回执' }).waitFor(); assert.equal(uploadRequests.filter(r => r.method === 'PUT').length, 2); checks.push('UI ZIP local validation -> 2 x 1 MiB chunks -> complete -> bundle import');
 const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: '导出 ZIP', exact: true }).click(); const download = await downloadPromise; const zipPath = resolve(out, '07-attachment-roundtrip.zip'); await download.saveAs(zipPath); const archive = readArchive(new Uint8Array(await readFile(zipPath))); const restored = validateBundle(JSON.parse(new TextDecoder().decode(archive['bundle.json']))); assert.equal(restored.attachments[0].status, 'available'); assert.deepEqual(archive[`attachments/${hash}`], bytes); assert.ok(restored.records.some(r => r.text === text)); checks.push('Actual downloaded ZIP readback preserves original bytes/hash + body');
 const beforeTamper = uploadRequests.length; await page.getByLabel('选择迁移包').setInputFiles({ name: 'tampered.zip', mimeType: 'application/zip', buffer: Buffer.from(zipSync({ 'bundle.json': strToU8(JSON.stringify(bundle)), [`attachments/${hash}`]: strToU8('wrong') })) }); await page.getByRole('alert').filter({ hasText: 'SHA-256' }).waitFor(); assert.equal(uploadRequests.length, beforeTamper); checks.push('Tampered ZIP blocked locally without upload');
 await page.goto(`${base}/library`); await page.getByLabel('搜索资料', { exact: true }).fill('隔离材料'); await page.waitForResponse(r => r.url().includes('/materials?q=') && r.request().method() === 'GET'); const rows = page.locator('.material-row'); assert.equal(await rows.count(), 25); await rows.first().locator('input[type=checkbox]').check(); await rows.nth(12).scrollIntoViewIfNeeded(); const beforeReaderScroll = await page.locator('#main-content').evaluate(el => el.scrollTop); assert.ok(beforeReaderScroll > 0); await rows.nth(12).locator('.material-row-main').click(); await page.locator('.reader-body').waitFor(); await page.getByRole('button', { name: '返回资料', exact: false }).click(); await page.waitForURL('**/library'); assert.equal(await page.getByLabel('搜索资料', { exact: true }).inputValue(), '隔离材料'); await page.getByText('已选 1 条', { exact: true }).waitFor(); await page.waitForFunction(value => Math.abs((document.getElementById('main-content')?.scrollTop || 0) - value) < 2, beforeReaderScroll); checks.push('Reader back preserves list filter, selection and scroll');
 await page.goto(`${base}/artifacts`); await page.getByRole('button', { name: '写一份成果', exact: true }).click(); let dialog = page.getByRole('dialog'); await dialog.getByLabel('标题').fill('超摘要引用成果'); await dialog.getByRole('button', { name: '创建草稿' }).click(); await page.waitForURL('**/artifacts/*'); const artifactURL = page.url(); await page.getByLabel('成果正文 Markdown').fill('引用完整原文中的明确证据。'); await page.getByRole('button', { name: '添加来源引用', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.locator('select').first().selectOption({ label: '超过六百字符与附件的隔离材料' }); await dialog.getByLabel('原文引句', { exact: false }).fill(quote); await dialog.getByRole('button', { name: '添加引用', exact: true }).click(); await page.getByRole('button', { name: '保存修改', exact: true }).click(); await page.locator('.citation-panel blockquote').filter({ hasText: quote }).waitFor(); const citationURL = await page.locator('.citation-panel a').first().getAttribute('href'); assert.match(citationURL || '', /revision=/); checks.push('Quote beyond 600-character list snippet validated from full detail');
 await page.getByRole('button', { name: '分享已保存稿', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('目标空间').selectOption(teamId); await dialog.getByLabel('同时分享原文快照').check(); await dialog.getByText('成果引用的原文尚未全部获准', { exact: false }).waitFor(); assert.ok(await dialog.getByRole('button', { name: '确认分享' }).isDisabled()); assert.equal(await dialog.getByRole('button', { name: '选中筛选结果' }).getAttribute('type'), 'button'); await dialog.getByRole('button', { name: '选中筛选结果' }).click(); assert.equal(await dialog.getByRole('heading', { name: '实际分享回执' }).count(), 0); await dialog.getByRole('button', { name: '确认分享' }).click(); await dialog.getByRole('heading', { name: '实际分享回执' }).waitFor(); await dialog.getByRole('button', { name: '完成', exact: true }).click(); checks.push('Team sharing demands explicitly approved cited source + actual receipt');
 await page.goto(`${base}/settings/models`); await page.getByRole('button', { name: '添加服务', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('名称', { exact: false }).first().fill('隔离提案模型 · 不调用'); await dialog.getByLabel('Base URL').fill('https://api.example.invalid/v1'); await dialog.getByLabel('默认模型 ID').fill('synthetic-manual-model'); await dialog.getByLabel('API Key', { exact: false }).fill('synthetic-not-a-real-key'); await dialog.getByRole('button', { name: '保存配置' }).click(); await page.getByRole('heading', { name: '隔离提案模型 · 不调用' }).waitFor();
 await page.goto(artifactURL); await page.getByRole('link', { name: '生成新提案', exact: true }).click(); await page.getByRole('button').filter({ hasText: '单帖深读' }).first().click(); await page.getByLabel('这次希望解决的问题').fill('在固定前稿基础上整理证据，不自动覆盖。'); await page.getByLabel('模型连接', { exact: false }).selectOption({ label: '隔离提案模型 · 不调用' }); await page.getByText('新增前稿不属于旧流程预授权', { exact: false }).waitFor(); assert.ok(await page.getByLabel('审批方式').isDisabled()); await page.getByRole('button', { name: '检查执行计划', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.getByText('新增外发前稿，强制', { exact: false }).waitFor(); await dialog.getByRole('button', { name: '建立待批准计划', exact: true }).click(); await page.waitForURL('**/tasks/*'); await page.getByRole('button', { name: '批准执行', exact: true }).waitFor(); await page.screenshot({ path: resolve(out, '08-proposal-manual-plan.png') }); checks.push('New target-artifact proposal creates real manual approval job; no model call');
 await page.goto(`${base}/library`); await page.getByRole('button', { name: '搜索资料', exact: false }).first().click(); dialog = page.getByRole('dialog'); assert.ok(await dialog.getByLabel('全局搜索关键词').evaluate(el => el === document.activeElement)); await page.keyboard.press('Escape'); assert.equal(await page.getByRole('dialog').count(), 0); checks.push('Search dialog keyboard autofocus / Escape restore');
 assert.deepEqual(errors, []); await writeFile(resolve(out, 'advanced-report.json'), JSON.stringify({ url: base, checks, pageErrors: errors, browser: await browser.version(), time: new Date().toISOString(), constraints: ['4320 isolated data only', 'no source login or collection', 'no provider requests; approval left pending', 'AI proposal generation/adoption needs isolated provider fixture separately'] }, null, 2)); console.log(JSON.stringify({ checks, pageErrors: errors }));
} catch (error) { console.error(JSON.stringify({ passedBeforeFailure: checks, url: page.url(), pageErrors: errors })); throw error; } finally { await browser.close(); }
