import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createBundle, fragmentsFor } from '../../shared/transfer';
const base = 'http://127.0.0.1:4320', out = resolve('web/test-output'); await mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true }), context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' }), page = await context.newPage();
const checks: string[] = [], errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(`${base}/register`); await page.getByLabel('称呼').fill('隔离千行验收'); await page.getByLabel('邮箱').fill(`large-${randomUUID()}@example.invalid`); await page.getByLabel('密码').fill(`Synthetic-${randomUUID()}!`); await page.getByRole('button', { name: '创建账号', exact: true }).click(); await page.waitForURL('**/inbox');
  const records = Array.from({ length: 1000 }, (_, index) => { const text = `千行隔离正文 ${index + 1}。这是合成验收材料，不访问源站。`; return { source_key: { platform: 'zsxq' as const, group_id: '700700', entity_type: 'topic' as const, entity_id: String(800000 + index) }, group_id: '700700', author_id: '900900', author_name: '长姓名'.repeat(25), title: `千行隔离材料 ${index + 1} · ${'长标题'.repeat(45)}`, text, created_at: '2026-10-01T00:00:00Z', captured_at: '2026-10-02T00:00:00Z', source_url: `https://wx.zsxq.com/dweb2/index/topic_detail/${800000 + index}/fixture-long-path-${'A'.repeat(500)}`, fragments: fragmentsFor(text), coverage: { body: 'complete' as const, comments: 'partial' as const, attachments: 'partial' as const, reasons: ['仅本地隔离 UI 验收'] } }; });
  await page.goto(`${base}/settings/data`); await page.getByLabel('选择迁移包').setInputFiles({ name: 'isolated-1000-records.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(createBundle({ records }))) }); await page.getByRole('button', { name: /^确认导入/ }).click(); await page.getByRole('heading', { name: '服务端导入回执', exact: true }).waitFor({ timeout: 90000 });
  await page.getByRole('link', { name: '查看资料库', exact: true }).click(); await page.waitForFunction(() => document.querySelectorAll('.material-row').length === 100); await page.getByText('1000 条资料', { exact: true }).waitFor();
  for (let index = 0; index < 9; index++) { await page.getByRole('button', { name: /再显示 100 条/ }).click(); await page.waitForFunction(count => document.querySelectorAll('.material-row').length === count, (index + 2) * 100); }
  assert.equal(await page.locator('.material-row').count(), 1000); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)); checks.push('Actual 1000-record API import/list; explicit 100-at-a-time rendering reaches all 1000 long titles/names without outer overflow');
  const row = page.locator('.material-row').nth(850); await row.scrollIntoViewIfNeeded(); const scroll = await page.locator('#main-content').evaluate(el => el.scrollTop); await row.locator('.material-row-main').click(); await page.locator('.reader-body').waitFor(); const source = await page.getByRole('link', { name: '查看原帖', exact: false }).getAttribute('href'); assert.ok(source && source.length > 500); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.getByRole('button', { name: '返回资料', exact: false }).click(); await page.waitForFunction(() => document.querySelectorAll('.material-row').length === 1000); await page.waitForFunction(value => Math.abs((document.getElementById('main-content')?.scrollTop || 0) - value) < 2, scroll); checks.push('Long source URL readable without request/overflow; return restores 1000-row expansion and far scroll');
  await context.setOffline(true); await page.getByRole('button', { name: '刷新材料', exact: true }).click(); await page.getByRole('alert').filter({ hasText: '无法连接工作台' }).waitFor(); assert.ok(await page.locator('.sidebar').isVisible());
  await context.setOffline(false); await page.getByRole('button', { name: '重试', exact: true }).click(); await page.waitForFunction(() => document.querySelectorAll('.material-row').length === 1000); checks.push('Offline refresh shows recoverable network error, not logout/success; reconnection restores actual list');
  assert.deepEqual(errors, []); await writeFile(resolve(out, 'large-list-report.json'), JSON.stringify({ url: base, checks, pageErrors: errors, browser: await browser.version(), time: new Date().toISOString(), constraints: ['4320 isolated account/materials only', 'real API writes of synthetic fixture, no source requests', 'not a sustained load or production capacity test'] }, null, 2)); console.log(JSON.stringify({ checks, pageErrors: errors }));
} catch (error) { console.error(JSON.stringify({ passedBeforeFailure: checks, url: page.url() })); throw error; } finally { await browser.close(); }
