// Isolated browser verification only. Never point this at the user instance.
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createBundle, fragmentsFor, sha256 } from '../../shared/transfer';
const base = process.env.WEB_REVIEW_URL || 'http://127.0.0.1:4320';
if (base !== 'http://127.0.0.1:4320') throw new Error('This check is pinned to the isolated review server on 4320.');
const out = resolve('web/test-output'); await mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true }); const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' }); const page = await context.newPage(); const errors: string[] = [], checks: string[] = [];
page.on('pageerror', e => errors.push(e.message)); const httpErrors: { path: string; status: number }[] = []; page.on('response', r => { if (r.url().startsWith(`${base}/api/`) && r.status() >= 400) httpErrors.push({ path: new URL(r.url()).pathname, status: r.status() }); });
const record = (title: string, text: string, captured: string) => ({ source_key: { platform: 'zsxq' as const, group_id: '100100', entity_type: 'topic' as const, entity_id: '200200' }, group_id: '100100', author_id: '300300', author_name: '隔离验收作者', title, text, created_at: '2026-10-01T00:00:00Z', source_url: 'https://wx.zsxq.com/dweb2/index/topic_detail/200200', coverage: { body: 'complete' as const, comments: 'partial' as const, attachments: 'partial' as const, reasons: ['隔离验收材料，未请求源站'] }, fragments: fragmentsFor(text), captured_at: captured, hash: sha256(text) });
try {
 await page.goto(`${base}/register`); await page.getByLabel('称呼').fill('隔离界面验收'); await page.getByLabel('邮箱').fill(`web-review-${randomUUID()}@example.invalid`); await page.getByLabel('密码').fill(`Synthetic-${randomUUID()}!`); await page.getByRole('button', { name: '创建账号', exact: true }).click(); await page.waitForURL('**/inbox'); await page.getByRole('heading', { name: '收件箱', exact: true }).waitFor(); await page.getByRole('heading', { name: '还没有待整理资料' }).waitFor(); checks.push('UI register / empty inbox'); await page.screenshot({ path: resolve(out, '01-inbox-desktop.png') });
 await page.goto(`${base}/settings/appearance`); await page.getByRole('button', { name: '石墨', exact: true }).click(); assert.equal(await page.locator('html').getAttribute('data-theme'), 'graphite'); await page.screenshot({ path: resolve(out, '02-graphite-settings.png') }); await page.getByRole('button', { name: '纸白', exact: true }).click(); await page.getByLabel('列表密度').selectOption('compact'); checks.push('Themes + persisted density');
 await page.goto(`${base}/connections`); await page.getByRole('button', { name: '连接知识星球', exact: true }).click(); let dialog = page.getByRole('dialog'); await dialog.getByLabel('连接名称').fill('隔离官方连接 · 未授权'); await dialog.getByLabel('官方 MCP', { exact: false }).first().check(); await dialog.getByLabel('官方 MCP 地址').fill('https://garden.zsxq.com/mcp/synthetic-not-authorized'); await dialog.getByRole('button', { name: '建立连接' }).click(); await page.getByRole('heading', { name: '隔离官方连接 · 未授权' }).waitFor(); checks.push('Official connection form / no outbound verification');
 await page.goto(`${base}/settings/models`); await page.getByRole('button', { name: '添加服务', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('名称', { exact: false }).first().fill('隔离模型配置 · 不调用'); await dialog.getByLabel('Base URL').fill('https://api.example.invalid/v1'); await dialog.getByLabel('默认模型 ID').fill('manual-model-a'); await dialog.getByLabel('API Key', { exact: false }).fill('synthetic-review-key-not-real'); await dialog.getByRole('button', { name: '保存配置' }).click(); await page.getByRole('heading', { name: '隔离模型配置 · 不调用' }).waitFor(); await page.getByRole('button', { name: '模型快捷切换' }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('手动模型 ID').fill('manual-model-b'); await dialog.getByRole('button', { name: '添加', exact: true }).click(); await dialog.getByRole('button', { name: '保存快捷模型' }).click(); await page.getByText('manual-model-b', { exact: true }).first().waitFor(); checks.push('Provider save + manual model selection without outbound call');
 const b = createBundle({ records: [record('旧版固定标题', '旧版原文第一句。\n保留换行与证据。', '2026-10-01T00:00:00Z'), record('新版固定标题', '新版原文第一句。\n保留换行与新的证据。', '2026-10-02T00:00:00Z')] }); await page.goto(`${base}/settings/data`); await page.getByLabel('选择迁移包').setInputFiles({ name: 'isolated-review.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(b)) }); await page.getByRole('button', { name: /^确认导入/ }).click(); await page.getByRole('heading', { name: '服务端导入回执' }).waitFor(); checks.push('Local validated preview + real API import receipt');
 await page.getByRole('link', { name: '查看资料库', exact: true }).click(); await page.getByRole('link', { name: /新版固定标题/ }).first().click(); await page.getByRole('heading', { name: '新版固定标题' }).waitFor(); const select = page.getByLabel('查看原文版本'); const option = await select.locator('option').last().getAttribute('value'); assert.ok(option); await select.selectOption(option); await page.getByRole('heading', { name: '旧版固定标题' }).waitFor(); assert.match(await page.locator('.reader-body').innerText(), /旧版原文第一句/); assert.match(page.url(), /revision=/); await page.screenshot({ path: resolve(out, '03-fixed-reader.png') }); checks.push('Historical title/text + fixed revision URL');
 await page.goto(`${base}/library`); await page.getByRole('button', { name: '保存当前筛选' }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('视图名称').fill('隔离保存视图'); await dialog.getByRole('button', { name: '保存视图' }).click(); await page.reload(); await page.getByRole('button', { name: '隔离保存视图', exact: true }).waitFor(); checks.push('User/workspace-scoped saved filter survives reload');
 await page.goto(`${base}/artifacts`); await page.getByRole('button', { name: '写一份成果', exact: true }).click(); dialog = page.getByRole('dialog'); await dialog.getByLabel('标题').fill('隔离手工成果'); await dialog.getByRole('button', { name: '创建草稿' }).click(); await page.waitForURL('**/artifacts/*'); await page.getByLabel('成果正文 Markdown').fill('## 固定证据\n\n| 项目 | 说明 |\n| --- | --- |\n| 隔离测试 | 没有源站采集 |\n\n- [x] 已人工检查\n\n```js\nconst value = 1;\n```\n\n<script>window.__xss = true</script>\n\n![追踪图](https://example.invalid/tracker.png)'); await page.getByRole('button', { name: '保存修改', exact: true }).click(); await page.getByRole('button', { name: '阅读预览', exact: true }).click(); await page.locator('.markdown-preview table').waitFor(); assert.equal(await page.locator('.markdown-preview img').count(), 0); assert.equal(await page.evaluate(() => (window as any).__xss), undefined); await page.screenshot({ path: resolve(out, '04-artifact-markdown.png') }); checks.push('Manual artifact saved + safe GFM table/code/task-list preview');
 await page.setViewportSize({ width: 375, height: 812 }); await page.goto(`${base}/inbox`); await page.getByRole('heading', { name: '收件箱', exact: true }).waitFor(); assert.ok(await page.locator('.mobile-bottom').isVisible()); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)); await page.screenshot({ path: resolve(out, '05-inbox-mobile.png') }); checks.push('375px mobile navigation / no horizontal overflow');
 await page.setViewportSize({ width: 900, height: 900 }); await page.goto(`${base}/settings/appearance`); assert.equal(await page.locator('.sidebar').evaluate(el => Math.round(el.getBoundingClientRect().width)), 72); await page.screenshot({ path: resolve(out, '06-tablet-settings.png') }); checks.push('900px collapsed navigation');
 assert.deepEqual(errors, []); await writeFile(resolve(out, 'render-report.json'), JSON.stringify({ url: base, checks, browser: await browser.version(), pageErrors: errors, time: new Date().toISOString(), constraints: ['isolated data only', 'no source login/collection', 'no model provider calls', 'AI proposal generation/adoption not exercised'] }, null, 2)); console.log(JSON.stringify({ checks, pageErrors: errors }));
} catch (error) { console.error(JSON.stringify({ passedBeforeFailure: checks, url: page.url(), httpErrors, pageErrors: errors, heading: await page.locator('h1').allTextContents() })); throw error; } finally { await browser.close(); }
